In [13]:
import matplotlib.pyplot as plt
import numpy as np

w = 3
Y, X = np.mgrid[-w:w:4j, -w:w:4j]

In [14]:
print(X)

[[-3. -1.  1.  3.]
 [-3. -1.  1.  3.]
 [-3. -1.  1.  3.]
 [-3. -1.  1.  3.]]


In [15]:
print(Y)

[[-3. -3. -3. -3.]
 [-1. -1. -1. -1.]
 [ 1.  1.  1.  1.]
 [ 3.  3.  3.  3.]]
